# Getting Started with DataJoint

In [1]:
import datajoint as dj

## Creating your first schema

In [2]:
schema = dj.schema('university')
schema.drop()
schema = dj.schema('university')

Connecting dbadmin@dimitri-proj0.cda95qzjbnvs.us-east-1.rds.amazonaws.com:3306
Proceed to delete entire schema `university`? [yes, No]: yes

## Creating your first table

In [3]:
@schema
class Student(dj.Manual):
    definition = """
    student_id : int unsigned   # university-wide ID number
    ---
    first_name      : varchar(40)
    last_name       : varchar(40)
    sex             : enum('F', 'M', 'U')
    """

### Inserting an entry as a dictionary

In [4]:
Student.insert1({
    'student_id': 1, 
    'first_name': 'Alice', 
    'last_name': 'Anderson', 
    'sex': 'F'})

In [5]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
 (Total: 1)

### Inserting an entry as a tuple

In [6]:
Student.insert1((2, 'Bob', 'Dylan', 'M'))

In [7]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
2              Bob            Dylan         M
 (Total: 2)

In [8]:
Student.insert1((3, 'Carol', 'Lewis', 'F'))

In [9]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
2              Bob            Dylan         M
3              Carol          Lewis         F
 (Total: 3)

### Inserting multiple entries as a list of dictionaries

In [10]:
students = [
    {'student_id': 4, 'first_name': 'Chris', 'last_name': 'Smith', 'sex': 'M'},
    {'student_id': 5, 'first_name': 'Stella', 'last_name': 'Taylor', 'sex': 'F'},
    {'student_id': 6, 'first_name': 'Max', 'last_name': 'Scott', 'sex': 'M'}
]
Student.insert(students)

In [11]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
2              Bob            Dylan         M
3              Carol          Lewis         F
4              Chris          Smith         M
5              Stella         Taylor        F
6              Max            Scott         M
 (Total: 6)

### Inserting multiple entries as a list of tuples

In [12]:
students = [
    (7, 'John', 'Allen', 'M'),
    (8, 'Julia', 'White', 'F'),
    (9, 'Emma', 'Reed', 'F')
]
Student.insert(students)

In [13]:
Student()

*student_id    first_name     last_name     sex
+------------+ +------------+ +-----------+ +-----+
1              Alice          Anderson      F
2              Bob            Dylan         M
3              Carol          Lewis         F
4              Chris          Smith         M
5              Stella         Taylor        F
6              Max            Scott         M
7              John           Allen         M
8              Julia          White         F
9              Emma           Reed          F
 (Total: 9)

### Dropping a table

In [14]:
Student.drop()

`university`.`student` (9 tuples)
Proceed? [yes, No]: yes
Tables dropped.  Restart kernel.

In [15]:
@schema
class Student(dj.Manual):
    definition = """
    student_id : int unsigned   # university-wide ID number
    ---
    first_name      : varchar(40)
    last_name       : varchar(40)
    sex             : enum('F', 'M', 'U')
    date_of_birth   : date
    home_address    : varchar(120) # mailing street address
    home_city       : varchar(60)  # mailing address
    home_state      : char(2)      # US state acronym: e.g. OH
    home_zip        : char(10)     # zipcode e.g. 93979-4979
    home_phone      : varchar(20)  # e.g. 414.657.6883x0881
    """

In [16]:
import insert_students

In [17]:
insert_students.insert(Student, 300)

In [18]:
Student()

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
0              Jillian        Fischer       F       2000-12-14     68627 Rodrigue East Anthony   WY             64660        +1-837-213-818
1              Danielle       Mccann        F       2001-07-10     459 Watts Path Lake Charles   PA             42226        2367757570
2              Gabriel        Austin        M       2002-05-15     59647 Bruce Gr New Alexander  OR             48511        +1-834-046-299
3              Gary           Adams         M       1990-12-30     2740 Henderson East Kyle      VA             16432        (652)366-4084x
4              Aaron          Dixon         M       2001-06-18     57205 Clark La Millermouth    AZ             90284        001-593-504-97
5              Mackenzie      Boyer         F       1988-12-26     9458 Ashley St Port Melissala OH             54499        669-684-3236
6              Bradley        Williams      M       1986-03-06     2067 Gonzalez  New Kayla      AK             12823        0458569751
7              Anthony        Diaz          M       1990-12-31     76723 Anthony  Sabrinabury    OR             42013        +1-183-571-071
8              Jacqueline     Colon         F       1996-02-24     64635 Duncan P Solisburgh     UT             76301        (983)027-5735x
9              Nicole         Long          F       1986-10-24     804 Sarah Rue  Port Kristinam ND             07732        568-928-6900x2
10             Brandon        Grant         M       1997-07-31     245 Christian  Ericside       ID             94059        6267113592
11             Kevin          Walker        M       2000-01-16     12139 Smith Hi Coleshire      OK             82926        001-227-524-14
   ...
 (Total: 300)

## Querying data

### Restricting by attribute values

In [19]:
Student() & 'sex="F"'

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
0              Jillian        Fischer       F       2000-12-14     68627 Rodrigue East Anthony   WY             64660        +1-837-213-818
1              Danielle       Mccann        F       2001-07-10     459 Watts Path Lake Charles   PA             42226        2367757570
5              Mackenzie      Boyer         F       1988-12-26     9458 Ashley St Port Melissala OH             54499        669-684-3236
8              Jacqueline     Colon         F       1996-02-24     64635 Duncan P Solisburgh     UT             76301        (983)027-5735x
9              Nicole         Long          F       1986-10-24     804 Sarah Rue  Port Kristinam ND             07732        568-928-6900x2
13             Anna           Golden        F       1999-03-09     177 Robles Por Jamesmouth     PA             57615        862.977.2190
14             Jessica        Ramos         F       1996-08-13     8318 Kenneth L North Megan    NJ             61279        (736)120-0323x
16             Heidi          Lewis         F       1992-03-07     810 Wanda Pine Nicholechester WA             39909        001-467-054-89
18             Dawn           Phillips      F       2004-08-30     9205 Margaret  East James     CA             35646        +1-986-030-376
19             Beth           Nielsen       F       1989-10-14     52211 Joseph C Port Amandaber WY             77459        001-289-285-46
20             Mikayla        Thomas        F       2003-10-03     3104 Riggs Rad Mathewsview    TX             41272        772.655.0583
22             Kristen        Wiley         F       2003-06-21     743 Linda Stre Christopherhav WI             29738        873-334-4318x1
   ...
 (Total: 151)

In [20]:
Student() & 'date_of_birth > "2000-01-01"'

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
0              Jillian        Fischer       F       2000-12-14     68627 Rodrigue East Anthony   WY             64660        +1-837-213-818
1              Danielle       Mccann        F       2001-07-10     459 Watts Path Lake Charles   PA             42226        2367757570
2              Gabriel        Austin        M       2002-05-15     59647 Bruce Gr New Alexander  OR             48511        +1-834-046-299
4              Aaron          Dixon         M       2001-06-18     57205 Clark La Millermouth    AZ             90284        001-593-504-97
11             Kevin          Walker        M       2000-01-16     12139 Smith Hi Coleshire      OK             82926        001-227-524-14
12             Bradley        Johnson       M       2002-10-27     44057 Amber Cl Martinborough  WA             96529        1246630797
17             Charles        Burns         M       2000-03-21     374 David Fork West Tylervill AR             66484        180-517-6772x0
18             Dawn           Phillips      F       2004-08-30     9205 Margaret  East James     CA             35646        +1-986-030-376
20             Mikayla        Thomas        F       2003-10-03     3104 Riggs Rad Mathewsview    TX             41272        772.655.0583
22             Kristen        Wiley         F       2003-06-21     743 Linda Stre Christopherhav WI             29738        873-334-4318x1
25             Dr.            Ashley        F       2005-03-16     1004 Fuller Ro South Gary     AR             14885        965.800.8174x1
29             Victoria       Rodriguez     F       2005-06-12     828 Lee Route  Lake Felicia   NC             44928        189.831.8711
   ...
 (Total: 96)

In [21]:
female_texans = Student & [{'sex': 'F'}, {'home_state': 'UT'}]

In [22]:
female_texans

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
0              Jillian        Fischer       F       2000-12-14     68627 Rodrigue East Anthony   WY             64660        +1-837-213-818
1              Danielle       Mccann        F       2001-07-10     459 Watts Path Lake Charles   PA             42226        2367757570
5              Mackenzie      Boyer         F       1988-12-26     9458 Ashley St Port Melissala OH             54499        669-684-3236
8              Jacqueline     Colon         F       1996-02-24     64635 Duncan P Solisburgh     UT             76301        (983)027-5735x
9              Nicole         Long          F       1986-10-24     804 Sarah Rue  Port Kristinam ND             07732        568-928-6900x2
13             Anna           Golden        F       1999-03-09     177 Robles Por Jamesmouth     PA             57615        862.977.2190
14             Jessica        Ramos         F       1996-08-13     8318 Kenneth L North Megan    NJ             61279        (736)120-0323x
16             Heidi          Lewis         F       1992-03-07     810 Wanda Pine Nicholechester WA             39909        001-467-054-89
18             Dawn           Phillips      F       2004-08-30     9205 Margaret  East James     CA             35646        +1-986-030-376
19             Beth           Nielsen       F       1989-10-14     52211 Joseph C Port Amandaber WY             77459        001-289-285-46
20             Mikayla        Thomas        F       2003-10-03     3104 Riggs Rad Mathewsview    TX             41272        772.655.0583
22             Kristen        Wiley         F       2003-06-21     743 Linda Stre Christopherhav WI             29738        873-334-4318x1
   ...
 (Total: 152)

## Fetching data from the querying results

In [23]:
female_texans.fetch()

array([(  0, 'Jillian', 'Fischer', 'F', datetime.date(2000, 12, 14), '68627 Rodriguez Center Suite 032', 'East Anthony', 'WY', '64660', '+1-837-213-8181x775'),
       (  1, 'Danielle', 'Mccann', 'F', datetime.date(2001, 7, 10), '459 Watts Path Suite 309', 'Lake Charles', 'PA', '42226', '2367757570'),
       (  5, 'Mackenzie', 'Boyer', 'F', datetime.date(1988, 12, 26), '9458 Ashley Stravenue Apt. 044', 'Port Melissaland', 'OH', '54499', '669-684-3236'),
       (  8, 'Jacqueline', 'Colon', 'F', datetime.date(1996, 2, 24), '64635 Duncan Place', 'Solisburgh', 'UT', '76301', '(983)027-5735x055'),
       (  9, 'Nicole', 'Long', 'F', datetime.date(1986, 10, 24), '804 Sarah Rue Suite 661', 'Port Kristinamouth', 'ND', '07732', '568-928-6900x28524'),
       ( 13, 'Anna', 'Golden', 'F', datetime.date(1999, 3, 9), '177 Robles Port', 'Jamesmouth', 'PA', '57615', '862.977.2190'),
       ( 14, 'Jessica', 'Ramos', 'F', datetime.date(1996, 8, 13), '8318 Kenneth Lakes', 'North Megan', 'NJ', '61279', '(736)120-0323x9695'),
       ( 16, 'Heidi', 'Lewis', 'F', datetime.date(1992, 3, 7), '810 Wanda Pines Suite 244', 'Nicholechester', 'WA', '39909', '001-467-054-8928x041'),
       ( 18, 'Dawn', 'Phillips', 'F', datetime.date(2004, 8, 30), '9205 Margaret Common Apt. 133', 'East James', 'CA', '35646', '+1-986-030-3766x9704'),
       ( 19, 'Beth', 'Nielsen', 'F', datetime.date(1989, 10, 14), '52211 Joseph Course', 'Port Amandaberg', 'WY', '77459', '001-289-285-4689'),
       ( 20, 'Mikayla', 'Thomas', 'F', datetime.date(2003, 10, 3), '3104 Riggs Radial Apt. 751', 'Mathewsview', 'TX', '41272', '772.655.0583'),
       ( 22, 'Kristen', 'Wiley', 'F', datetime.date(2003, 6, 21), '743 Linda Street Suite 948', 'Christopherhaven', 'WI', '29738', '873-334-4318x117'),
       ( 24, 'Karen', 'Hall', 'F', datetime.date(1991, 1, 1), '802 Oconnor Shoal', 'Courtneyside', 'VA', '76699', '001-450-895-2937x557'),
       ( 25, 'Dr.', 'Ashley', 'F', datetime.date(2005, 3, 16), '1004 Fuller Route Suite 401', 'South Gary', 'AR', '14885', '965.800.8174x14559'),
       ( 27, 'Tara', 'Moore', 'F', datetime.date(1996, 9, 25), '09753 Timothy Plains Suite 918', 'South Brandichester', 'WV', '20935', '098-675-6040'),
       ( 29, 'Victoria', 'Rodriguez', 'F', datetime.date(2005, 6, 12), '828 Lee Route', 'Lake Felicia', 'NC', '44928', '189.831.8711'),
       ( 30, 'Debbie', 'Patterson', 'F', datetime.date(1994, 8, 29), '5977 Donald Hills Suite 426', 'North Jillian', 'VA', '86148', '573-589-7894'),
       ( 31, 'Karen', 'Lee', 'F', datetime.date(2001, 5, 28), '92397 Smith Court Suite 681', 'New Robin', 'OR', '03775', '001-504-939-0893x736'),
       ( 33, 'Kimberly', 'Carey', 'F', datetime.date(1998, 9, 7), '92403 Nancy Mills Apt. 662', 'Port Laurenside', 'NY', '99368', '(097)580-1867x2670'),
       ( 34, 'Robin', 'Jones', 'F', datetime.date(1991, 4, 4), '872 Jackson Pines Suite 396', 'Youngborough', 'MA', '74118', '+1-092-142-9264x4959'),
       ( 37, 'Heather', 'Humphrey', 'F', datetime.date(2000, 3, 12), '728 Amy Groves Apt. 457', 'South Alvin', 'IN', '27823', '4145328004'),
       ( 38, 'Jasmine', 'Hicks', 'F', datetime.date(1986, 6, 22), '92100 Nunez Mountain Suite 341', 'New Rachaelside', 'DC', '53689', '5590657043'),
       ( 39, 'Amanda', 'Wang', 'F', datetime.date(2002, 7, 9), '028 James Avenue', 'Donnaburgh', 'NV', '37215', '251-324-2667'),
       ( 40, 'Amanda', 'Rosario', 'F', datetime.date(1999, 4, 10), '9563 Michael Pine Suite 931', 'Michaelshire', 'WV', '21208', '001-576-734-7225x242'),
       ( 43, 'Amanda', 'Arroyo', 'F', datetime.date(1992, 4, 30), '49408 Williams Brook', 'Jennifermouth', 'NE', '68506', '126-624-6833'),
       ( 45, 'Kelly', 'Wheeler', 'F', datetime.date(1999, 8, 28), '5199 Grace Stream', 'North Regina', 'ID', '42797', '(852)471-1509x6905'),
       ( 48, 'Kimberly', 'Raymond', 'F', datetime.date(2004, 1, 28), '69277 Ray Key', 'South Danielletown', 'ID', '64803', '022.172.5672x603'),
       ( 51, 'Deanna', 'Valdez', 'F', datetime.date(2001, 10, 20), '98307 Jennifer Track', 'South Johnmouth', 'FL', '54437', '788.587.3743'),
       ( 53, 'Kristen', 'Jenkins', 'F', datetime.date(1989, 12, 6), '7196 Brian Center', 'Barbaraview', 'NE', '95825', '+1-816-931-7241x906'),
       ( 54, 'Jessica', 'Bennett', 'F', datetime.date(2003, 8, 26), '615 Sharon Gateway', 'Port Sean', 'SC', '03709', '867.612.4267x9135'),
       ( 55, 'Elizabeth', 'Howell', 'F', datetime.date(2002, 9, 4), '2352 Benjamin Gateway Suite 996', 'Josephburgh', 'IL', '50989', '001-719-428-3855'),
       ( 56, 'Dr.', 'Bethany', 'F', datetime.date(2003, 9, 14), '074 Justin Spurs Apt. 653', 'West Davidview', 'WA', '58491', '839-843-6610'),
       ( 59, 'Kristina', 'Kirby', 'F', datetime.date(1988, 5, 22), '89489 Young Way', 'Benjaminstad', 'ID', '20962', '+1-494-205-1237x9988'),
       ( 61, 'Carolyn', 'Miller', 'F', datetime.date(2002, 9, 18), '955 Brandon Mill Suite 104', 'Tuckerton', 'IN', '83326', '308.665.7407'),
       ( 64, 'Ashley', 'Young', 'F', datetime.date(2000, 2, 22), '36721 Simpson Lights Suite 035', 'Smithberg', 'OK', '84539', '733.287.7040'),
       ( 66, 'Kristin', 'Mason', 'F', datetime.date(1987, 4, 14), '31397 Stone Parkway Suite 353', 'Lake Amanda', 'DC', '09007', '696.480.4255x92770'),
       ( 67, 'Megan', 'Martinez', 'F', datetime.date(1994, 12, 22), '5276 Alexander Avenue Suite 928', 'North Rodney', 'KY', '62441', '(432)914-1079'),
       ( 68, 'Janet', 'Anderson', 'F', datetime.date(2002, 6, 28), '206 Smith Viaduct Suite 699', 'Heiditon', 'SD', '81142', '529.788.9930'),
       ( 69, 'Vanessa', 'Copeland', 'F', datetime.date(1995, 10, 28), '9695 Samuel Drive Suite 092', 'Christopherburgh', 'WI', '51730', '915-931-4672x9407'),
       ( 70, 'Kathleen', 'Reed', 'F', datetime.date(1999, 8, 11), '41882 Allen Walk Apt. 899', 'Sandrabury', 'LA', '56451', '+1-106-887-8907x7524'),
       ( 71, 'Katherine', 'Jenkins', 'F', datetime.date(1998, 12, 2), '51656 Joseph Rapid Apt. 522', 'New Richardville', 'KY', '63822', '+1-522-727-7641x7839'),
       ( 74, 'Katherine', 'Potter', 'F', datetime.date(2005, 3, 17), '477 Carrillo Street', 'West Emily', 'RI', '62414', '164.047.7857'),
       ( 75, 'Teresa', 'Carter', 'F', datetime.date(1996, 2, 26), '597 Aimee Locks', 'Johnfurt', 'NE', '45270', '408-191-1318x661'),
       ( 77, 'Rachel', 'Bowen', 'F', datetime.date(2002, 5, 25), '547 Taylor Crest', 'Kellytown', 'ME', '61328', '707-544-3298x4719'),
       ( 78, 'Emily', 'Jones', 'F', datetime.date(2001, 10, 18), '502 Cameron Estate', 'South Thomas', 'OK', '51464', '001-280-466-4043x825'),
       ( 79, 'Jennifer', 'Nunez', 'F', datetime.date(1989, 3, 1), '158 James Green Apt. 156', 'West Jerry', 'CA', '77440', '(571)077-8320'),
       ( 80, 'Jennifer', 'Nguyen', 'F', datetime.date(1993, 11, 10), '6937 Jennifer Lock Apt. 321', 'Deanstad', 'NY', '48675', '001-267-589-2918x447'),
       ( 81, 'Jessica', 'Clay', 'F', datetime.date(1997, 5, 22), '536 Hernandez Walks Apt. 972', 'South Alanmouth', 'SD', '96555', '6697468738'),
       ( 83, 'Kristin', 'Jones', 'F', datetime.date(1990, 4, 17), '10480 Walker Trail Apt. 498', 'New Robertland', 'RI', '01171', '+1-421-682-5503x016'),
       ( 86, 'Andrea', 'Moreno', 'F', datetime.date(1990, 11, 24), '5411 Smith Ways', 'Sanchezberg', 'LA', '26114', '001-988-175-2362'),
       ( 91, 'Sara', 'Huff', 'F', datetime.date(2005, 2, 20), '017 Rich Hills Suite 633', 'Brownchester', 'CT', '67581', '(933)377-7739x6876'),
       ( 96, 'Kimberly', 'Butler', 'F', datetime.date(1994, 10, 13), '48400 Rodriguez Street', 'Lake Robertstad', 'KS', '77376', '6395340351'),
       ( 97, 'Tracy', 'Baker', 'F', datetime.date(2001, 2, 1), '79211 Nathaniel Drive Suite 386', 'South Deannashire', 'IL', '28281', '+1-005-844-5959'),
       (101, 'Andrea', 'Franklin', 'F', datetime.date(1996, 6, 9), '4446 Taylor Plaza', 'Port Davidside', 'AR', '93278', '493-991-1706x07012'),
       (102, 'Alyssa', 'Brown', 'F', datetime.date(2004, 6, 9), '20243 Daniel Manor Apt. 402', 'Cynthiaberg', 'MN', '22079', '001-925-888-7154x436'),
       (107, 'Brenda', 'Sanders', 'F', datetime.date(1990, 4, 25), '189 Stephen Knolls', 'Lake Amyborough', 'AR', '93809', '453.136.2198'),
       (109, 'Deanna', 'Cox', 'F', datetime.date(2003, 9, 24), '164 Chapman Drive Apt. 274', 'South Robert', 'NC', '28885', '(235)873-8575'),
       (111, 'Heather', 'Alvarado', 'F', datetime.date(2003, 2, 8), '042 Rebecca Mission', 'North Donna', 'MD', '87937', '803.854.9834'),
       (116, 'Amber', 'Blankenship', 'F', datetime.date(1993, 12, 12), '41843 Jones Heights', 'Port Kara', 'CT', '78824', '+1-632-246-1077x531'),
       (117, 'Kathryn', 'Davis', 'F', datetime.date(1994, 6, 26), '71512 Nicholas Rapids', 'Port Traciberg', 'MA', '84122', '001-011-104-2980x973'),
       (118, 'Kristina', 'Norman', 'F', datetime.date(2005, 3, 4), '5665 Dennis Mill', 'Perkinschester', 'PA', '38683', '816-936-8115x18690'),
       (119, 'Alicia', 'Sweeney', 'F', datetime.date(1996, 2, 6), '111 Mackenzie Junctions', 'West Linda', 'IN', '93938', '894-678-6968x11463'),
       (122, 'Rebecca', 'Copeland', 'F', datetime.date(1994, 12, 13), '89462 Lewis Expressway Apt. 713', 'Haleymouth', 'NY', '78212', '+1-614-640-8342x007'),
       (123, 'Anna', 'Cunningham', 'F', datetime.date(2000, 1, 23), '293 Cox Pine', 'Kruegerborough', 'TN', '94115', '095.131.3694'),
       (125, 'Kylie', 'Diaz', 'F', datetime.date(2003, 8, 17), '4603 Douglas Fort Apt. 494', 'Colemanview', 'WI', '03325', '052.106.6014x95876'),
       (126, 'Kristin', 'Yates', 'F', datetime.date(1989, 9, 26), '7297 Danielle Wells Apt. 787', 'Bruceview', 'AK', '01608', '471-379-8060'),
       (127, 'Kayla', 'Sawyer', 'F', datetime.date(1987, 4, 1), '147 Peter Crest', 'Medinamouth', 'SC', '36063', '155.903.2519x32943'),
       (128, 'Megan', 'Rodriguez', 'F', datetime.date(1990, 10, 23), '9126 Brown Plaza', 'New David', 'MD', '28416', '924-150-2547'),
       (132, 'Deborah', 'Callahan', 'F', datetime.date(1992, 9, 21), '8147 Madison Wells', 'Moyerbury', 'MN', '55249', '815.014.3670'),
       (133, 'Natalie', 'Thomas', 'F', datetime.date(2000, 4, 29), '18291 Marcus Lock Apt. 641', 'Carlosmouth', 'LA', '41866', '007.913.3881x94110'),
       (137, 'Melanie', 'Miller', 'F', datetime.date(1994, 1, 4), '1921 Michael Courts', 'Thomasberg', 'TN', '95425', '+1-392-739-5934x213'),
       (138, 'Amber', 'Peters', 'F', datetime.date(1995, 9, 4), '501 Burnett Inlet', 'West Brittany', 'VT', '08798', '853-889-0428x9721'),
       (139, 'Kristen', 'Thomas', 'F', datetime.date(1993, 5, 31), '10941 Virginia Island', 'Penningtonhaven', 'IN', '79891', '(192)078-6665'),
       (144, 'Samantha', 'Clark', 'F', datetime.date(1996, 6, 1), '9094 Owens Causeway Suite 106', 'Martinezland', 'WY', '49371', '975.309.8113x664'),
       (148, 'Felicia', 'Vaughn', 'F', datetime.date(2001, 8, 5), '90380 Joshua Landing', 'New Steven', 'SD', '37352', '+1-918-046-4526x727'),
       (149, 'Debra', 'West', 'F', datetime.date(2003, 11, 9), '49508 Kelly Springs', 'Hallland', 'MD', '01505', '(428)591-2046x3225'),
       (151, 'Melissa', 'Thomas', 'F', datetime.date(2002, 6, 5), '454 Mike Walk Suite 188', 'Sarashire', 'IN', '93084', '(707)472-4151x17712'),
       (154, 'Tanya', 'Williams', 'F', datetime.date(1985, 11, 19), '427 Ann Isle Apt. 757', 'West Kristinaville', 'CO', '45548', '001-440-604-4666x725'),
       (155, 'Emily', 'Byrd', 'F', datetime.date(2004, 4, 3), '650 Roberts Road', 'West Zacharyfort', 'WY', '79775', '(443)399-6944'),
       (157, 'Monica', 'Klein', 'F', datetime.date(1998, 12, 9), '53050 Garcia Street Apt. 359', 'Butlerstad', 'DE', '87791', '+1-510-661-1680'),
       (158, 'Crystal', 'Leach', 'F', datetime.date(1991, 12, 17), '88760 Elizabeth Station', 'East Scott', 'IN', '76311', '717.446.6353x0889'),
       (160, 'Maureen', 'Simon', 'F', datetime.date(1996, 10, 5), '9799 Julie Plaza Suite 583', 'Barryport', 'IN', '87386', '+1-365-486-0536x712'),
       (161, 'Wendy', 'Mcclure', 'F', datetime.date(2005, 5, 13), '93627 Hansen Drives', 'New Lisa', 'KS', '01367', '968.733.9273x1230'),
       (162, 'Veronica', 'Jackson', 'F', datetime.date(1987, 9, 10), '55017 Anna Viaduct', 'Michaelbury', 'MN', '76244', '(354)996-9659x86033'),
       (164, 'Amy', 'Williams', 'F', datetime.date(1998, 7, 29), '334 Weeks Club Suite 643', 'Larsonborough', 'ME', '18462', '409-286-7863'),
       (168, 'Alyssa', 'Guerra', 'F', datetime.date(1989, 12, 10), '5551 John Stream', 'West Erikafort', 'TX', '39968', '+1-384-619-7074'),
       (169, 'Deborah', 'Cline', 'F', datetime.date(1996, 3, 3), '91196 Anthony Wells', 'Brownhaven', 'MT', '23238', '(671)274-4744x719'),
       (171, 'Diana', 'Wagner', 'F', datetime.date(2005, 10, 21), '957 Wong Lights', 'East Matthew', 'MA', '01000', '(282)563-2014x87937'),
       (172, 'Tracy', 'Patton', 'F', datetime.date(2005, 4, 6), '82521 Brooks Tunnel Apt. 807', 'West Richardhaven', 'NH', '27416', '856.087.2857'),
       (173, 'Taylor', 'Fleming', 'F', datetime.date(1992, 12, 8), '96752 Villa Stream Apt. 607', 'North Sarahchester', 'LA', '55882', '642-759-4869x1650'),
       (175, 'Melissa', 'Keller', 'F', datetime.date(1994, 8, 23), '2874 Saunders Glen Suite 317', 'Denisebury', 'TN', '65422', '(484)124-9158x3337'),
       (176, 'Crystal', 'Short', 'F', datetime.date(1996, 10, 11), '14918 Brown Walk', 'West Jeff', 'IN', '19394', '001-611-275-1179x645'),
       (182, 'Katie', 'Palmer', 'F', datetime.date(1989, 8, 24), '439 Wright Prairie Suite 796', 'Fullerborough', 'ME', '03583', '+1-438-161-7483x788'),
       (184, 'Jordan', 'Jones', 'F', datetime.date(1993, 8, 29), '227 Christy Causeway Suite 269', 'Port Brandonchester', 'CT', '34678', '(152)951-9193x444'),
       (187, 'Kimberly', 'Anthony', 'F', datetime.date(1996, 1, 15), '71203 Ray Spur', 'Torrestown', 'KY', '09573', '(786)320-7649x2637'),
       (188, 'Ashley', 'Guzman', 'F', datetime.date(2001, 11, 14), '011 Fowler Drive Apt. 620', 'Garciamouth', 'MI', '94068', '001-809-948-0078x762'),
       (189, 'Kelly', 'Thompson', 'F', datetime.date(2004, 4, 26), '33144 Jeffery Courts Suite 171', 'North Isaiah', 'OR', '50923', '001-437-662-7268x603'),
       (192, 'Margaret', 'Hughes', 'F', datetime.date(1986, 11, 17), '4879 Michelle Land Suite 673', 'Jenniferstad', 'PA', '27286', '001-390-553-2632'),
       (193, 'Lisa', 'Escobar', 'F', datetime.date(1998, 3, 13), '926 Stark Crossing', 'South Bryan', 'MS', '86227', '(331)589-7870x58178'),
       (198, 'Sarah', 'Odonnell', 'F', datetime.date(1989, 9, 13), '18158 Ellison Hills Apt. 244', 'Travisfurt', 'AL', '04641', '(792)274-1066x26038'),
       (199, 'Stephanie', 'Curtis', 'F', datetime.date(1995, 11, 14), '133 Christopher Junction Apt. 134', 'South Jennifer', 'CA', '62643', '614-287-6200x23188'),
       (200, 'Kimberly', 'Taylor', 'F', datetime.date(1987, 8, 14), '42166 Flores Island', 'Roberthaven', 'MT', '17048', '+1-689-653-0999'),
       (201, 'Lacey', 'Taylor', 'F', datetime.date(1988, 4, 26), '97005 Lisa Mill Suite 678', 'Newtonshire', 'TN', '69198', '+1-357-502-7339x1514'),
       (202, 'Melissa', 'Little', 'F', datetime.date(1999, 7, 13), '383 Haynes Court', 'North Lindsey', 'NY', '29588', '024.540.9045'),
       (206, 'Karen', 'Bryan', 'F', datetime.date(1999, 6, 13), '3670 Carol Village Suite 907', 'South Christinaville', 'GA', '37283', '001-359-306-4754x614'),
       (207, 'Anita', 'Harmon', 'F', datetime.date(1995, 6, 27), '9485 Werner Underpass', 'Jeffreyview', 'WV', '39997', '064.111.8438'),
       (208, 'Beth', 'Smith', 'F', datetime.date(2004, 9, 30), '958 Kimberly Forges', 'Newmanland', 'NE', '78284', '492.071.6510'),
       (209, 'Carrie', 'Dennis', 'F', datetime.date(1993, 11, 12), '3666 Adams Vista', 'North Jenniferland', 'SD', '02830', '+1-395-365-9523x6997'),
       (210, 'Paula', 'Perez', 'F', datetime.date(2000, 8, 15), '17911 Frazier Roads', 'Port Tasha', 'UT', '21725', '405.906.1669'),
       (213, 'Brianna', 'Rose', 'F', datetime.date(1998, 3, 31), '0428 Gomez Trail Apt. 639', 'North Donna', 'WA', '26718', '001-823-285-7191x368'),
       (220, 'Kathryn', 'Lopez', 'F', datetime.date(1988, 3, 25), '861 Tanya Knolls', 'Payneside', 'NJ', '90616', '(074)095-3943x06918'),
       (221, 'Sarah', 'Myers', 'F', datetime.date(1993, 1, 26), '34262 Christopher Street', 'Cabrerabury', 'HI', '26895', '915.044.0595'),
       (224, 'Donna', 'Smith', 'F', datetime.date(2004, 12, 19), '804 Mccoy Turnpike Suite 847', 'Bautistafurt', 'WI', '29114', '(046)527-9112x706'),
       (226, 'Shelley', 'Brooks', 'F', datetime.date(2005, 9, 27), '31828 Taylor Glen Suite 101', 'New Jenniferhaven', 'NJ', '44670', '+1-491-708-0414x864'),
       (228, 'Andrea', 'Barrett', 'F', datetime.date(1993, 8, 11), '7100 Scott Lake', 'Kristenstad', 'OK', '09274', '001-500-223-8945x457'),
       (234, 'Katelyn', 'Hoover', 'F', datetime.date(1997, 12, 24), '9315 Christopher Road', 'Loriburgh', 'CA', '75454', '275.704.7134x661'),
       (235, 'Shannon', 'Williams', 'F', datetime.date(2002, 7, 8), '08663 Kimberly Expressway Apt. 575', 'South Wyatt', 'AL', '80993', '314-058-0010'),
       (239, 'Yvette', 'Galloway', 'F', datetime.date(2002, 7, 24), '12076 Anthony Square', 'Samueltown', 'NY', '34260', '(878)866-9801x91611'),
       (241, 'Sandra', 'Winters', 'F', datetime.date(2005, 7, 31), '907 Mario Lodge Apt. 942', 'Shermanville', 'ND', '45545', '+1-753-365-4045'),
       (248, 'Richard', 'Noble', 'M', datetime.date(2003, 2, 5), '7977 Adams Crossroad Suite 214', 'Port Catherineland', 'UT', '34911', '458.117.5719'),
       (249, 'Ashley', 'Thomas', 'F', datetime.date(1996, 8, 29), '241 Katie Fort Apt. 087', 'New Ebony', 'ME', '26233', '135-652-0859x3049'),
       (251, 'Ashley', 'Miller', 'F', datetime.date(1988, 6, 13), '1805 Alexis Villages', 'Morrisonton', 'MD', '93116', '(263)336-5912'),
       (254, 'Deanna', 'Price', 'F', datetime.date(1994, 11, 4), '120 Edwards Expressway Suite 511', 'Kathleenberg', 'CA', '19876', '001-940-447-1052x158'),
       (258, 'Julie', 'Jones', 'F', datetime.date(2005, 8, 2), '35304 Rachel Meadows Suite 288', 'North Jeffreyberg', 'AZ', '48886', '141-934-7302x6340'),
       (259, 'Monica', 'Hill', 'F', datetime.date(1992, 10, 18), '945 Angela Key', 'Johnchester', 'GA', '23266', '0750320331'),
       (260, 'Joanne', 'Williams', 'F', datetime.date(2001, 2, 7), '85254 Janet Pines', 'Lake Daniel', 'AZ', '34031', '623.410.2275'),
       (262, 'Debra', 'Riggs', 'F', datetime.date(2002, 5, 3), '090 Andrew Mountains Apt. 054', 'New Amandachester', 'WA', '61679', '001-635-536-1950x612'),
       (264, 'Heidi', 'Charles', 'F', datetime.date(1990, 3, 15), '927 Chandler Groves Suite 929', 'Leeville', 'MA', '27167', '(160)618-6264x340'),
       (266, 'Valerie', 'Smith', 'F', datetime.date(1989, 1, 22), '4709 Patrick Wall', 'West Ericview', 'AL', '73935', '(783)138-7164'),
       (268, 'Debra', 'Schmitt', 'F', datetime.date(1992, 12, 22), '74229 James Hills Apt. 780', 'East Kristina', 'IN', '43119', '516.311.9867'),
       (269, 'Veronica', 'Anderson', 'F', datetime.date(1997, 5, 19), '0043 Baker Springs', 'Kristinaton', 'UT', '04908', '(811)585-2197x666'),
       (271, 'Elizabeth', 'Brock', 'F', datetime.date(1987, 3, 6), '8230 Mitchell Extension Apt. 275', 'Port Anthony', 'CA', '31032', '190-577-0466x2936'),
       (273, 'Brenda', 'Lynch', 'F', datetime.date(2002, 9, 10), '11630 Jeremy Mountains', 'Austinchester', 'SC', '45091', '(460)652-5911x142'),
       (275, 'Diane', 'Walker', 'F', datetime.date(2002, 6, 22), '929 Olivia Turnpike', 'Lake Keithport', 'DE', '11107', '1672377368'),
       (276, 'Sara', 'Murphy', 'F', datetime.date(1987, 7, 5), '178 Smith Prairie', 'West Allison', 'ND', '93840', '610.384.6473x01662'),
       (278, 'Shannon', 'Mayer', 'F', datetime.date(1997, 4, 10), '8730 Derrick Mews Suite 666', 'Craneborough', 'NV', '24146', '001-006-189-0389x612'),
       (279, 'Crystal', 'Parker', 'F', datetime.date(2001, 11, 28), '1314 Jessica Causeway', 'Port Stephen', 'GA', '98006', '(321)139-5367'),

In [24]:
female_texans.fetch(as_dict=True)

[{'student_id': 0,
  'first_name': 'Jillian',
  'last_name': 'Fischer',
  'sex': 'F',
  'date_of_birth': datetime.date(2000, 12, 14),
  'home_address': '68627 Rodriguez Center Suite 032',
  'home_city': 'East Anthony',
  'home_state': 'WY',
  'home_zip': '64660',
  'home_phone': '+1-837-213-8181x775'},
 {'student_id': 1,
  'first_name': 'Danielle',
  'last_name': 'Mccann',
  'sex': 'F',
  'date_of_birth': datetime.date(2001, 7, 10),
  'home_address': '459 Watts Path Suite 309',
  'home_city': 'Lake Charles',
  'home_state': 'PA',
  'home_zip': '42226',
  'home_phone': '2367757570'},
 {'student_id': 5,
  'first_name': 'Mackenzie',
  'last_name': 'Boyer',
  'sex': 'F',
  'date_of_birth': datetime.date(1988, 12, 26),
  'home_address': '9458 Ashley Stravenue Apt. 044',
  'home_city': 'Port Melissaland',
  'home_state': 'OH',
  'home_zip': '54499',
  'home_phone': '669-684-3236'},
 {'student_id': 8,
  'first_name': 'Jacqueline',
  'last_name': 'Colon',
  'sex': 'F',
  'date_of_birth': datetime.date(1996, 2, 24),
  'home_address': '64635 Duncan Place',
  'home_city': 'Solisburgh',
  'home_state': 'UT',
  'home_zip': '76301',
  'home_phone': '(983)027-5735x055'},
 {'student_id': 9,
  'first_name': 'Nicole',
  'last_name': 'Long',
  'sex': 'F',
  'date_of_birth': datetime.date(1986, 10, 24),
  'home_address': '804 Sarah Rue Suite 661',
  'home_city': 'Port Kristinamouth',
  'home_state': 'ND',
  'home_zip': '07732',
  'home_phone': '568-928-6900x28524'},
 {'student_id': 13,
  'first_name': 'Anna',
  'last_name': 'Golden',
  'sex': 'F',
  'date_of_birth': datetime.date(1999, 3, 9),
  'home_address': '177 Robles Port',
  'home_city': 'Jamesmouth',
  'home_state': 'PA',
  'home_zip': '57615',
  'home_phone': '862.977.2190'},
 {'student_id': 14,
  'first_name': 'Jessica',
  'last_name': 'Ramos',
  'sex': 'F',
  'date_of_birth': datetime.date(1996, 8, 13),
  'home_address': '8318 Kenneth Lakes',
  'home_city': 'North Megan',
  'home_state': 'NJ',
  'home_zip': '61279',
  'home_phone': '(736)120-0323x9695'},
 {'student_id': 16,
  'first_name': 'Heidi',
  'last_name': 'Lewis',
  'sex': 'F',
  'date_of_birth': datetime.date(1992, 3, 7),
  'home_address': '810 Wanda Pines Suite 244',
  'home_city': 'Nicholechester',
  'home_state': 'WA',
  'home_zip': '39909',
  'home_phone': '001-467-054-8928x041'},
 {'student_id': 18,
  'first_name': 'Dawn',
  'last_name': 'Phillips',
  'sex': 'F',
  'date_of_birth': datetime.date(2004, 8, 30),
  'home_address': '9205 Margaret Common Apt. 133',
  'home_city': 'East James',
  'home_state': 'CA',
  'home_zip': '35646',
  'home_phone': '+1-986-030-3766x9704'},
 {'student_id': 19,
  'first_name': 'Beth',
  'last_name': 'Nielsen',
  'sex': 'F',
  'date_of_birth': datetime.date(1989, 10, 14),
  'home_address': '52211 Joseph Course',
  'home_city': 'Port Amandaberg',
  'home_state': 'WY',
  'home_zip': '77459',
  'home_phone': '001-289-285-4689'},
 {'student_id': 20,
  'first_name': 'Mikayla',
  'last_name': 'Thomas',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 10, 3),
  'home_address': '3104 Riggs Radial Apt. 751',
  'home_city': 'Mathewsview',
  'home_state': 'TX',
  'home_zip': '41272',
  'home_phone': '772.655.0583'},
 {'student_id': 22,
  'first_name': 'Kristen',
  'last_name': 'Wiley',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 6, 21),
  'home_address': '743 Linda Street Suite 948',
  'home_city': 'Christopherhaven',
  'home_state': 'WI',
  'home_zip': '29738',
  'home_phone': '873-334-4318x117'},
 {'student_id': 24,
  'first_name': 'Karen',
  'last_name': 'Hall',
  'sex': 'F',
  'date_of_birth': datetime.date(1991, 1, 1),
  'home_address': '802 Oconnor Shoal',
  'home_city': 'Courtneyside',
  'home_state': 'VA',
  'home_zip': '76699',
  'home_phone': '001-450-895-2937x557'},
 {'student_id': 25,
  'first_name': 'Dr.',
  'last_name': 'Ashley',
  'sex': 'F',
  'date_of_birth': datetime.date(2005, 3, 16),
  'home_address': '1004 Fuller Route Suite 401',
  'home_city': 'South Gary',
  'home_state': 'AR',
  'home_zip': '14885',
  'home_phone': '965.800.8174x14559'},
 {'student_id': 27,
  'first_name': 'Tara',
  'last_name': 'Moore',
  'sex': 'F',
  'date_of_birth': datetime.date(1996, 9, 25),
  'home_address': '09753 Timothy Plains Suite 918',
  'home_city': 'South Brandichester',
  'home_state': 'WV',
  'home_zip': '20935',
  'home_phone': '098-675-6040'},
 {'student_id': 29,
  'first_name': 'Victoria',
  'last_name': 'Rodriguez',
  'sex': 'F',
  'date_of_birth': datetime.date(2005, 6, 12),
  'home_address': '828 Lee Route',
  'home_city': 'Lake Felicia',
  'home_state': 'NC',
  'home_zip': '44928',
  'home_phone': '189.831.8711'},
 {'student_id': 30,
  'first_name': 'Debbie',
  'last_name': 'Patterson',
  'sex': 'F',
  'date_of_birth': datetime.date(1994, 8, 29),
  'home_address': '5977 Donald Hills Suite 426',
  'home_city': 'North Jillian',
  'home_state': 'VA',
  'home_zip': '86148',
  'home_phone': '573-589-7894'},
 {'student_id': 31,
  'first_name': 'Karen',
  'last_name': 'Lee',
  'sex': 'F',
  'date_of_birth': datetime.date(2001, 5, 28),
  'home_address': '92397 Smith Court Suite 681',
  'home_city': 'New Robin',
  'home_state': 'OR',
  'home_zip': '03775',
  'home_phone': '001-504-939-0893x736'},
 {'student_id': 33,
  'first_name': 'Kimberly',
  'last_name': 'Carey',
  'sex': 'F',
  'date_of_birth': datetime.date(1998, 9, 7),
  'home_address': '92403 Nancy Mills Apt. 662',
  'home_city': 'Port Laurenside',
  'home_state': 'NY',
  'home_zip': '99368',
  'home_phone': '(097)580-1867x2670'},
 {'student_id': 34,
  'first_name': 'Robin',
  'last_name': 'Jones',
  'sex': 'F',
  'date_of_birth': datetime.date(1991, 4, 4),
  'home_address': '872 Jackson Pines Suite 396',
  'home_city': 'Youngborough',
  'home_state': 'MA',
  'home_zip': '74118',
  'home_phone': '+1-092-142-9264x4959'},
 {'student_id': 37,
  'first_name': 'Heather',
  'last_name': 'Humphrey',
  'sex': 'F',
  'date_of_birth': datetime.date(2000, 3, 12),
  'home_address': '728 Amy Groves Apt. 457',
  'home_city': 'South Alvin',
  'home_state': 'IN',
  'home_zip': '27823',
  'home_phone': '4145328004'},
 {'student_id': 38,
  'first_name': 'Jasmine',
  'last_name': 'Hicks',
  'sex': 'F',
  'date_of_birth': datetime.date(1986, 6, 22),
  'home_address': '92100 Nunez Mountain Suite 341',
  'home_city': 'New Rachaelside',
  'home_state': 'DC',
  'home_zip': '53689',
  'home_phone': '5590657043'},
 {'student_id': 39,
  'first_name': 'Amanda',
  'last_name': 'Wang',
  'sex': 'F',
  'date_of_birth': datetime.date(2002, 7, 9),
  'home_address': '028 James Avenue',
  'home_city': 'Donnaburgh',
  'home_state': 'NV',
  'home_zip': '37215',
  'home_phone': '251-324-2667'},
 {'student_id': 40,
  'first_name': 'Amanda',
  'last_name': 'Rosario',
  'sex': 'F',
  'date_of_birth': datetime.date(1999, 4, 10),
  'home_address': '9563 Michael Pine Suite 931',
  'home_city': 'Michaelshire',
  'home_state': 'WV',
  'home_zip': '21208',
  'home_phone': '001-576-734-7225x242'},
 {'student_id': 43,
  'first_name': 'Amanda',
  'last_name': 'Arroyo',
  'sex': 'F',
  'date_of_birth': datetime.date(1992, 4, 30),
  'home_address': '49408 Williams Brook',
  'home_city': 'Jennifermouth',
  'home_state': 'NE',
  'home_zip': '68506',
  'home_phone': '126-624-6833'},
 {'student_id': 45,
  'first_name': 'Kelly',
  'last_name': 'Wheeler',
  'sex': 'F',
  'date_of_birth': datetime.date(1999, 8, 28),
  'home_address': '5199 Grace Stream',
  'home_city': 'North Regina',
  'home_state': 'ID',
  'home_zip': '42797',
  'home_phone': '(852)471-1509x6905'},
 {'student_id': 48,
  'first_name': 'Kimberly',
  'last_name': 'Raymond',
  'sex': 'F',
  'date_of_birth': datetime.date(2004, 1, 28),
  'home_address': '69277 Ray Key',
  'home_city': 'South Danielletown',
  'home_state': 'ID',
  'home_zip': '64803',
  'home_phone': '022.172.5672x603'},
 {'student_id': 51,
  'first_name': 'Deanna',
  'last_name': 'Valdez',
  'sex': 'F',
  'date_of_birth': datetime.date(2001, 10, 20),
  'home_address': '98307 Jennifer Track',
  'home_city': 'South Johnmouth',
  'home_state': 'FL',
  'home_zip': '54437',
  'home_phone': '788.587.3743'},
 {'student_id': 53,
  'first_name': 'Kristen',
  'last_name': 'Jenkins',
  'sex': 'F',
  'date_of_birth': datetime.date(1989, 12, 6),
  'home_address': '7196 Brian Center',
  'home_city': 'Barbaraview',
  'home_state': 'NE',
  'home_zip': '95825',
  'home_phone': '+1-816-931-7241x906'},
 {'student_id': 54,
  'first_name': 'Jessica',
  'last_name': 'Bennett',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 8, 26),
  'home_address': '615 Sharon Gateway',
  'home_city': 'Port Sean',
  'home_state': 'SC',
  'home_zip': '03709',
  'home_phone': '867.612.4267x9135'},
 {'student_id': 55,
  'first_name': 'Elizabeth',
  'last_name': 'Howell',
  'sex': 'F',
  'date_of_birth': datetime.date(2002, 9, 4),
  'home_address': '2352 Benjamin Gateway Suite 996',
  'home_city': 'Josephburgh',
  'home_state': 'IL',
  'home_zip': '50989',
  'home_phone': '001-719-428-3855'},
 {'student_id': 56,
  'first_name': 'Dr.',
  'last_name': 'Bethany',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 9, 14),
  'home_address': '074 Justin Spurs Apt. 653',
  'home_city': 'West Davidview',
  'home_state': 'WA',
  'home_zip': '58491',
  'home_phone': '839-843-6610'},
 {'student_id': 59,
  'first_name': 'Kristina',
  'last_name': 'Kirby',
  'sex': 'F',
  'date_of_birth': datetime.date(1988, 5, 22),
  'home_address': '89489 Young Way',
  'home_city': 'Benjaminstad',
  'home_state': 'ID',
  'home_zip': '20962',
  'home_phone': '+1-494-205-1237x9988'},
 {'student_id': 61,
  'first_name': 'Carolyn',
  'last_name': 'Miller',
  'sex': 'F',
  'date_of_birth': datetime.date(2002, 9, 18),
  'home_address': '955 Brandon Mill Suite 104',
  'home_city': 'Tuckerton',
  'home_state': 'IN',
  'home_zip': '83326',
  'home_phone': '308.665.7407'},
 {'student_id': 64,
  'first_name': 'Ashley',
  'last_name': 'Young',
  'sex': 'F',
  'date_of_birth': datetime.date(2000, 2, 22),
  'home_address': '36721 Simpson Lights Suite 035',
  'home_city': 'Smithberg',
  'home_state': 'OK',
  'home_zip': '84539',
  'home_phone': '733.287.7040'},
 {'student_id': 66,
  'first_name': 'Kristin',
  'last_name': 'Mason',
  'sex': 'F',
  'date_of_birth': datetime.date(1987, 4, 14),
  'home_address': '31397 Stone Parkway Suite 353',
  'home_city': 'Lake Amanda',
  'home_state': 'DC',
  'home_zip': '09007',
  'home_phone': '696.480.4255x92770'},
 {'student_id': 67,
  'first_name': 'Megan',
  'last_name': 'Martinez',
  'sex': 'F',
  'date_of_birth': datetime.date(1994, 12, 22),
  'home_address': '5276 Alexander Avenue Suite 928',
  'home_city': 'North Rodney',
  'home_state': 'KY',
  'home_zip': '62441',
  'home_phone': '(432)914-1079'},
 {'student_id': 68,
  'first_name': 'Janet',
  'last_name': 'Anderson',
  'sex': 'F',
  'date_of_birth': datetime.date(2002, 6, 28),
  'home_address': '206 Smith Viaduct Suite 699',
  'home_city': 'Heiditon',
  'home_state': 'SD',
  'home_zip': '81142',
  'home_phone': '529.788.9930'},
 {'student_id': 69,
  'first_name': 'Vanessa',
  'last_name': 'Copeland',
  'sex': 'F',
  'date_of_birth': datetime.date(1995, 10, 28),
  'home_address': '9695 Samuel Drive Suite 092',
  'home_city': 'Christopherburgh',
  'home_state': 'WI',
  'home_zip': '51730',
  'home_phone': '915-931-4672x9407'},
 {'student_id': 70,
  'first_name': 'Kathleen',
  'last_name': 'Reed',
  'sex': 'F',
  'date_of_birth': datetime.date(1999, 8, 11),
  'home_address': '41882 Allen Walk Apt. 899',
  'home_city': 'Sandrabury',
  'home_state': 'LA',
  'home_zip': '56451',
  'home_phone': '+1-106-887-8907x7524'},
 {'student_id': 71,
  'first_name': 'Katherine',
  'last_name': 'Jenkins',
  'sex': 'F',
  'date_of_birth': datetime.date(1998, 12, 2),
  'home_address': '51656 Joseph Rapid Apt. 522',
  'home_city': 'New Richardville',
  'home_state': 'KY',
  'home_zip': '63822',
  'home_phone': '+1-522-727-7641x7839'},
 {'student_id': 74,
  'first_name': 'Katherine',
  'last_name': 'Potter',
  'sex': 'F',
  'date_of_birth': datetime.date(2005, 3, 17),
  'home_address': '477 Carrillo Street',
  'home_city': 'West Emily',
  'home_state': 'RI',
  'home_zip': '62414',
  'home_phone': '164.047.7857'},
 {'student_id': 75,
  'first_name': 'Teresa',
  'last_name': 'Carter',
  'sex': 'F',
  'date_of_birth': datetime.date(1996, 2, 26),
  'home_address': '597 Aimee Locks',
  'home_city': 'Johnfurt',
  'home_state': 'NE',
  'home_zip': '45270',
  'home_phone': '408-191-1318x661'},
 {'student_id': 77,
  'first_name': 'Rachel',
  'last_name': 'Bowen',
  'sex': 'F',
  'date_of_birth': datetime.date(2002, 5, 25),
  'home_address': '547 Taylor Crest',
  'home_city': 'Kellytown',
  'home_state': 'ME',
  'home_zip': '61328',
  'home_phone': '707-544-3298x4719'},
 {'student_id': 78,
  'first_name': 'Emily',
  'last_name': 'Jones',
  'sex': 'F',
  'date_of_birth': datetime.date(2001, 10, 18),
  'home_address': '502 Cameron Estate',
  'home_city': 'South Thomas',
  'home_state': 'OK',
  'home_zip': '51464',
  'home_phone': '001-280-466-4043x825'},
 {'student_id': 79,
  'first_name': 'Jennifer',
  'last_name': 'Nunez',
  'sex': 'F',
  'date_of_birth': datetime.date(1989, 3, 1),
  'home_address': '158 James Green Apt. 156',
  'home_city': 'West Jerry',
  'home_state': 'CA',
  'home_zip': '77440',
  'home_phone': '(571)077-8320'},
 {'student_id': 80,
  'first_name': 'Jennifer',
  'last_name': 'Nguyen',
  'sex': 'F',
  'date_of_birth': datetime.date(1993, 11, 10),
  'home_address': '6937 Jennifer Lock Apt. 321',
  'home_city': 'Deanstad',
  'home_state': 'NY',
  'home_zip': '48675',
  'home_phone': '001-267-589-2918x447'},
 {'student_id': 81,
  'first_name': 'Jessica',
  'last_name': 'Clay',
  'sex': 'F',
  'date_of_birth': datetime.date(1997, 5, 22),
  'home_address': '536 Hernandez Walks Apt. 972',
  'home_city': 'South Alanmouth',
  'home_state': 'SD',
  'home_zip': '96555',
  'home_phone': '6697468738'},
 {'student_id': 83,
  'first_name': 'Kristin',
  'last_name': 'Jones',
  'sex': 'F',
  'date_of_birth': datetime.date(1990, 4, 17),
  'home_address': '10480 Walker Trail Apt. 498',
  'home_city': 'New Robertland',
  'home_state': 'RI',
  'home_zip': '01171',
  'home_phone': '+1-421-682-5503x016'},
 {'student_id': 86,
  'first_name': 'Andrea',
  'last_name': 'Moreno',
  'sex': 'F',
  'date_of_birth': datetime.date(1990, 11, 24),
  'home_address': '5411 Smith Ways',
  'home_city': 'Sanchezberg',
  'home_state': 'LA',
  'home_zip': '26114',
  'home_phone': '001-988-175-2362'},
 {'student_id': 91,
  'first_name': 'Sara',
  'last_name': 'Huff',
  'sex': 'F',
  'date_of_birth': datetime.date(2005, 2, 20),
  'home_address': '017 Rich Hills Suite 633',
  'home_city': 'Brownchester',
  'home_state': 'CT',
  'home_zip': '67581',
  'home_phone': '(933)377-7739x6876'},
 {'student_id': 96,
  'first_name': 'Kimberly',
  'last_name': 'Butler',
  'sex': 'F',
  'date_of_birth': datetime.date(1994, 10, 13),
  'home_address': '48400 Rodriguez Street',
  'home_city': 'Lake Robertstad',
  'home_state': 'KS',
  'home_zip': '77376',
  'home_phone': '6395340351'},
 {'student_id': 97,
  'first_name': 'Tracy',
  'last_name': 'Baker',
  'sex': 'F',
  'date_of_birth': datetime.date(2001, 2, 1),
  'home_address': '79211 Nathaniel Drive Suite 386',
  'home_city': 'South Deannashire',
  'home_state': 'IL',
  'home_zip': '28281',
  'home_phone': '+1-005-844-5959'},
 {'student_id': 101,
  'first_name': 'Andrea',
  'last_name': 'Franklin',
  'sex': 'F',
  'date_of_birth': datetime.date(1996, 6, 9),
  'home_address': '4446 Taylor Plaza',
  'home_city': 'Port Davidside',
  'home_state': 'AR',
  'home_zip': '93278',
  'home_phone': '493-991-1706x07012'},
 {'student_id': 102,
  'first_name': 'Alyssa',
  'last_name': 'Brown',
  'sex': 'F',
  'date_of_birth': datetime.date(2004, 6, 9),
  'home_address': '20243 Daniel Manor Apt. 402',
  'home_city': 'Cynthiaberg',
  'home_state': 'MN',
  'home_zip': '22079',
  'home_phone': '001-925-888-7154x436'},
 {'student_id': 107,
  'first_name': 'Brenda',
  'last_name': 'Sanders',
  'sex': 'F',
  'date_of_birth': datetime.date(1990, 4, 25),
  'home_address': '189 Stephen Knolls',
  'home_city': 'Lake Amyborough',
  'home_state': 'AR',
  'home_zip': '93809',
  'home_phone': '453.136.2198'},
 {'student_id': 109,
  'first_name': 'Deanna',
  'last_name': 'Cox',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 9, 24),
  'home_address': '164 Chapman Drive Apt. 274',
  'home_city': 'South Robert',
  'home_state': 'NC',
  'home_zip': '28885',
  'home_phone': '(235)873-8575'},
 {'student_id': 111,
  'first_name': 'Heather',
  'last_name': 'Alvarado',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 2, 8),
  'home_address': '042 Rebecca Mission',
  'home_city': 'North Donna',
  'home_state': 'MD',
  'home_zip': '87937',
  'home_phone': '803.854.9834'},
 {'student_id': 116,
  'first_name': 'Amber',
  'last_name': 'Blankenship',
  'sex': 'F',
  'date_of_birth': datetime.date(1993, 12, 12),
  'home_address': '41843 Jones Heights',
  'home_city': 'Port Kara',
  'home_state': 'CT',
  'home_zip': '78824',
  'home_phone': '+1-632-246-1077x531'},
 {'student_id': 117,
  'first_name': 'Kathryn',
  'last_name': 'Davis',
  'sex': 'F',
  'date_of_birth': datetime.date(1994, 6, 26),
  'home_address': '71512 Nicholas Rapids',
  'home_city': 'Port Traciberg',
  'home_state': 'MA',
  'home_zip': '84122',
  'home_phone': '001-011-104-2980x973'},
 {'student_id': 118,
  'first_name': 'Kristina',
  'last_name': 'Norman',
  'sex': 'F',
  'date_of_birth': datetime.date(2005, 3, 4),
  'home_address': '5665 Dennis Mill',
  'home_city': 'Perkinschester',
  'home_state': 'PA',
  'home_zip': '38683',
  'home_phone': '816-936-8115x18690'},
 {'student_id': 119,
  'first_name': 'Alicia',
  'last_name': 'Sweeney',
  'sex': 'F',
  'date_of_birth': datetime.date(1996, 2, 6),
  'home_address': '111 Mackenzie Junctions',
  'home_city': 'West Linda',
  'home_state': 'IN',
  'home_zip': '93938',
  'home_phone': '894-678-6968x11463'},
 {'student_id': 122,
  'first_name': 'Rebecca',
  'last_name': 'Copeland',
  'sex': 'F',
  'date_of_birth': datetime.date(1994, 12, 13),
  'home_address': '89462 Lewis Expressway Apt. 713',
  'home_city': 'Haleymouth',
  'home_state': 'NY',
  'home_zip': '78212',
  'home_phone': '+1-614-640-8342x007'},
 {'student_id': 123,
  'first_name': 'Anna',
  'last_name': 'Cunningham',
  'sex': 'F',
  'date_of_birth': datetime.date(2000, 1, 23),
  'home_address': '293 Cox Pine',
  'home_city': 'Kruegerborough',
  'home_state': 'TN',
  'home_zip': '94115',
  'home_phone': '095.131.3694'},
 {'student_id': 125,
  'first_name': 'Kylie',
  'last_name': 'Diaz',
  'sex': 'F',
  'date_of_birth': datetime.date(2003, 8, 17),
  'home_address': '4603 Douglas Fort Apt. 494',
  'home_city': 'Colemanview',
  'home_state': 'WI',
  'home_zip': '03325',
  'home_phone': '052.106.6014x95876'},
 {'student_id': 126,
  'first_name': 'Kristin',
  'last_name': 'Yates',
  'sex': 'F',
  'date_of_birth': datetime.date(1989, 9, 26),
  'home_address': '7297 Danielle Wells Apt. 787',
  'home_city': 'Bruceview',
  'home_state': 'AK',
  'home_zip': '01608',
  'home_phone': '471-379-8060'},
 {'student_id': 127,
  'first_name': 'Kayla',
  'last_name': 'Sawyer',
  'sex': 'F',
  'date_of_birth': datetime.date(1987, 4, 1),
  'home_address': '147 Peter Crest',
  'home_city': 'Medinamouth',
  'home_state': 'SC',
  'home_zip': '36063',
  'home_phone': '155.903.2519x32943'},
 {'student_id': 128,
  'first_name': 'Megan',
  'last_name': 'Rodriguez',
  'sex': 'F',
  'date_of_birth': datetime.date(1990, 10, 23),
  'home_address': '9126 Brown Plaza',
  'home_city': 'New David',
  'home_state': 'MD',
  'home_zip': '28416',
  'home_phone': '924-150-2547'},
 {'student_id': 132,
  'first_name': 'Deborah',
  'last_name': 'Callahan',
  'sex': 'F',
  'date_of_birth': datetime.date(1992, 9, 21),
  'home_address': '8147 Madison Wells',
  'home_city': 'Moyerbury',
  'home_state': 'MN',
  'home_zip': '55249',

In [25]:
female_texans.fetch(format="frame")

,first_name,last_name,sex,date_of_birth,home_address,home_city,home_state,home_zip,home_phone
student_id,,,,,,,,,
0,Jillian,Fischer,F,2000-12-14,68627 Rodriguez Center Suite 032,East Anthony,WY,64660,+1-837-213-8181x775
1,Danielle,Mccann,F,2001-07-10,459 Watts Path Suite 309,Lake Charles,PA,42226,2367757570
5,Mackenzie,Boyer,F,1988-12-26,9458 Ashley Stravenue Apt. 044,Port Melissaland,OH,54499,669-684-3236
8,Jacqueline,Colon,F,1996-02-24,64635 Duncan Place,Solisburgh,UT,76301,(983)027-5735x055
9,Nicole,Long,F,1986-10-24,804 Sarah Rue Suite 661,Port Kristinamouth,ND,07732,568-928-6900x28524
...,...,...,...,...,...,...,...,...,...
291,Shari,Rodriguez,F,2002-04-07,14993 Reeves Cove,East Frederick,MN,14832,436.215.4569x041
292,Wendy,Mathews,F,2003-12-13,8728 Jamie Courts,New Leefort,AL,66380,+1-716-103-4197x654
296,Michelle,George,F,1994-01-02,56285 Stephanie Wall Suite 800,Vazquezside,AR,02142,(683)009-1622x26181
298,Christine,Johnson,F,2003-02-14,4725 Petersen Via,Clarkburgh,NC,75437,+1-281-129-5589x225
299,Lisa,Sheppard,F,2004-04-02,95923 Reynolds Fork Suite 719,West Laura,LA,23546,001-842-369-3244x325

In [26]:
len(female_texans)

152

In [27]:
utahns = Student & {'home_state': 'UT'}

In [28]:
utah_genz = utahns & 'date_of_birth > "1989-01-01"'

In [29]:
utah_genz

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
8              Jacqueline     Colon         F       1996-02-24     64635 Duncan P Solisburgh     UT             76301        (983)027-5735x
210            Paula          Perez         F       2000-08-15     17911 Frazier  Port Tasha     UT             21725        405.906.1669
248            Richard        Noble         M       2003-02-05     7977 Adams Cro Port Catherine UT             34911        458.117.5719
269            Veronica       Anderson      F       1997-05-19     0043 Baker Spr Kristinaton    UT             04908        (811)585-2197x
 (Total: 4)

In [30]:
utah_genz

*student_id    first_name     last_name     sex     date_of_birth  home_address   home_city      home_state     home_zip     home_phone
+------------+ +------------+ +-----------+ +-----+ +------------+ +------------+ +------------+ +------------+ +----------+ +------------+
8              Jacqueline     Colon         F       1996-02-24     64635 Duncan P Solisburgh     UT             76301        (983)027-5735x
210            Paula          Perez         F       2000-08-15     17911 Frazier  Port Tasha     UT             21725        405.906.1669
248            Richard        Noble         M       2003-02-05     7977 Adams Cro Port Catherine UT             34911        458.117.5719
269            Veronica       Anderson      F       1997-05-19     0043 Baker Spr Kristinaton    UT             04908        (811)585-2197x
 (Total: 4)

In [31]:
utah_genz.heading.table_status

{'name': 'student',
 'engine': 'InnoDB',
 'version': 10,
 'row_format': 'Dynamic',
 'rows': 0,
 'avg_row_length': 0,
 'data_length': 16384,
 'max_data_length': 0,
 'index_length': 0,
 'data_free': 0,
 'auto_increment': None,
 'create_time': datetime.datetime(2020, 10, 27, 9, 45, 43),
 'update_time': None,
 'check_time': None,
 'collation': 'latin1_swedish_ci',
 'checksum': None,
 'create_options': '',
 'comment': ''}

In [32]:
utah_genz = utah_genz.proj('last_name', 'home_city','home_state','sex')
utah_genz

*student_id    last_name     sex     home_city      home_state
+------------+ +-----------+ +-----+ +------------+ +------------+
8              Colon         F       Solisburgh     UT
210            Perez         F       Port Tasha     UT
248            Noble         M       Port Catherine UT
269            Anderson      F       Kristinaton    UT
 (Total: 4)

In [33]:
utah_genz.heading.non_blobs

['student_id', 'last_name', 'sex', 'home_city', 'home_state']